version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - |
        if [ $Env = "prod" ]; then
          echo 'prod env'
        else
          echo 'non prod env'
        fi
artifacts:
  files: '**/*'