version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo '$env'
      - echo $env
      - chmod +x ./my-script.sh
      - ./my-script.sh
artifacts:
  files: '**/*'