version: 0.2

env:
  variables:
    MY_VAR: "prod"

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo '$env'
      - echo $env
      - | 
          if [ "${env}" = "${MY_VAR}" ];then
            echo 'prod' 1>&2
          else
            echo 'non prod' 
          fi
      - |
        if [ -z "${AWS_REGION}" ]; then 
          echo "AWS_REGION variable not set" 1>&2
        else
          echo "AWS_REGION=${AWS_REGION}"
        fi
artifacts:
  files: '**/*'