version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
    # - aws cloudformation deploy --stack-name data-collection-codepipeline-$env-stack --template-file codepipeline-non-prod.yaml --parameter-overrides Project=$project Environment=$env Department=$department Owner=$owner GithubUsername=$githubuser RepoName=$reponame BranchName=$branch OAuthtoken=$oauthtoken --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
    
      - if expr "${evn}" : "prod" >/dev/null; then echo 'prod'; else echo 'non prod'; fi
    
    # - aws cloudformation deploy --stack-name data-collection-codepipeline-$env-stack --template-file codepipeline-prod.yaml --parameter-overrides Project=$project Environment=$env Department=$department Owner=$owner GithubUsername=$githubuser RepoName=$reponame BranchName=$branch OAuthtoken=$oauthtoken --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
artifacts:
  files: '**/*'