version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - if expr "${evn}" : "prod" >/dev/null; then echo 'prod'; else echo 'non prod'; fi
artifacts:
  files: '**/*'